### ISSUE TITLE
Missing ./configs/config_unet_mean_shift.yaml

### ISSUE THREAD

**Issue by thorikawa** [svip-lab/PlanarReconstruction#2]
Hi,

Thank you for uploading the code! I am trying myself and have a problem while evaluating. 

The error message is as below:
```
Traceback (most recent call last):
  File "main.py", line 542, in <module>
    ex.add_config('./configs/config_unet_mean_shift.yaml')
  File "/home/poly/anaconda3/envs/py36/lib/python3.6/site-packages/sacred/ingredient.py", line 195, in add_config
    kw_conf))
  File "/home/poly/anaconda3/envs/py36/lib/python3.6/site-packages/sacred/ingredient.py", line 216, in _create_config_dict
    raise IOError('File not found {}'.format(cfg_or_file))
OSError: File not found ./configs/config_unet_mean_shift.yaml
```

Can you share your config_unet_mean_shift.yaml or am I missing something to generate this?

Thanks in advance.

**Comment by niujinshuchong** [comment]
@thorikawa I forgot to add config file. It's updated.
