### ISSUE TITLE
KeyError: '.yaml'

### ISSUE THREAD

**Issue by XGuider** [svip-lab/PlanarReconstruction#5]
Thank you for uploading the code! I am trying myself and have a problem while train.

if __name__ == '__main__':
    assert LooseVersion(torch.__version__) >= LooseVersion('0.4.0'), \
        'PyTorch>=0.4.0 is required'

    ex.add_config('/home/user/Desktop/AFA/PlanarReconstruction-master/configs/config_unet_mean_shift.yaml')#this is my path
    ex.run_commandline()

The error message is as below:

Traceback (most recent call last):
  File "/home/user/Desktop/AFA/PlanarReconstruction-master/main.py", line 542, in <module>
    ex.add_config('/home/user/Desktop/AFA/PlanarReconstruction-master/configs/config_unet_mean_shift.yaml')
  File "/home/user/.local/lib/python3.6/site-packages/sacred/ingredient.py", line 195, in add_config
    kw_conf))
  File "/home/user/.local/lib/python3.6/site-packages/sacred/ingredient.py", line 218, in _create_config_dict
    return ConfigDict(load_config_file(abspath))
  File "/home/user/.local/lib/python3.6/site-packages/sacred/config/config_files.py", line 41, in load_config_file
    handler = get_handler(filename)
  File "/home/user/.local/lib/python3.6/site-packages/sacred/config/config_files.py", line 37, in get_handler
    return HANDLER_BY_EXT[extension]
KeyError: '.yaml'

thnx you help

**Comment by bertjiazheng** [comment]
It seems something related to package `sacred`. Since we use `yaml` as our config file, please make sure that you have installed `pyyaml`.

**Comment by XGuider** [comment]
@bertjiazheng thnx!
